apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-app
  namespace: test
spec:
  selector:
    matchLabels:
      app: java
  strategy:
    type: RollingUpdate
  replicas: 2
  template:
    metadata:
      name: java-web-app-pod
      namespace: test
      labels:
        app: java
    spec:
    containers:
    - name: java-web-app-container
      image: bpavani/java-web-app:latest
      ports:
       - containerPort: 8080

